FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY fullchain.pem /etc/letsencrypt/live/lanplay.splatnet2.com/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/lanplay.splatnet2.com/privkey.pem 
